name: pixiv_dart_api
description: Pixiv Dart API
version: 2.0.1
homepage: https://pixiv.xiaocao.site/#/pixiv-api/dart
repository: https://github.com/xiao-cao-x/pixiv_dart_api

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  dio: ^4.0.6
  json_annotation: ^4.4.0
  crypto: ^3.0.1
dev_dependencies:
  json_serializable: ^6.1.4
  build_runner: ^2.1.10